version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd:1.0.2-1
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - ./files/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf

  grafana:
    image: grafana/grafana:4.4.2
    ports:
      - "3000:3000"
